# Generated by Django 4.2.5 on 2023-09-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=150, verbose_name='ФИО')),
                ('university', models.CharField(max_length=200, verbose_name='учебное заведение')),
                ('tel', models.CharField(max_length=11, verbose_name='телефон')),
                ('email', models.CharField(max_length=255, verbose_name='email')),
            ],
        ),
    ]
